:backend: revealjs
:revealjs_theme: moon

= Listes
:source-highlighter: pygments
:pygments-style: tango

== Définition et syntaxe

Une liste est un "ensemble" d'objets indicés.

La syntaxe est la suivante:

[source,python]
----
>>> course = ["beurre","tomates","PQ" ]
----

== !

[source,python]
----
>>> ma_liste = [42, "toto", [4,5]]
----

Une liste peut contenir plusieurs types différents, dont des listes.

=== Accéder

On peut accéder à un élément particulier d'une liste à l'aide de son index dans la liste:

[source,python]
----
>>> course = ["beurre","tomates","PQ" ]
>>> course[2]
'PQ'
----

Comme pour les chaînes de caractères.

=== !

[source,python]
----
>>> course = ["beurre","tomates","PQ" ]
>>> course[0]
'beurre'
----

Attention on commence à compter à partir de 0.

=== Modifier

On peut modifier un élément de la liste de la sorte:

[source,python]
----
>>> course[1] = "carrotes"
>>> course
 ['beurre', 'carrotes', 'PQ']
----

=== Ajouter
On peut ajouter un élément à la fin de la liste de la sorte:

[source,python]
----
>>> course.append("lait")
>>> course
 ['beurre', 'carrotes', 'PQ', 'lait']
----

=== Supprimer

Et supprimer un élément selon son indice:
[source,python]
----
>>> del(course[2])
>>> course
 ['beurre', 'carrotes', 'lait']
----

=== Mesurer

On peut obtenir la longueur d'une liste avec la fonction `len`

[source,python]
----
>>> len(course)
 5
----

Comme pour les chaînes de caractères.

=== Parcourir

On peut parcourir une liste de plusieurs façons:

[source,python]
----
>>> for i in course:
...     print(i)
...
beurre
carrotes
lait
huile
PQ
----


[source,python]
----
>>> for i in range(len(course)):
...     print(course[i])
...
beurre
carrotes
lait
huile
PQ
----

== Passer des chaînes de caractères aux listes et inversement


=== Transformer une chaîne de caractères en liste

La fonction `list` permet de transformer une chaîne de caractère en une liste.

[source,python]
----
>>> ma_liste = list("hello")
>>> ma_liste
['h', 'e', 'l', 'l', 'o']
----

=== Transformer une liste en une chaîne de caractères

La méthode `join` permet de concaténer une liste dans une chaîne de caractère.

[source,python]
----
>>> ma_chaine = "".join(["w","o","r","l","d"])
>>> ma_chaine
"world"
----

=== Application

[source,python]
----
mot = input("Entrez un mot:")
lettres = list(mot)
for i in range(len(lettres)):
    if lettres[i] == "a":
        lettres[i] = "@"
mot_affiche = "".join(lettres)
print(mot_affiche)
----
