:backend: revealjs
:revealjs_theme: moon

= VI. Fonctions
:source-highlighter: pygments
:pygments-style: tango

== 1. Introduction

Observons le code suivant:

link:https://trinket.io/library/trinkets/6d7c32db00[Liste des vols]

=== !


L'instruction est répété trois fois.

[source,python]
----
print("----------------------------------------")
print()
print()
----

Si on décide de modifier l'affichage, il faut le modifier trois fois !

=== !

Au lieu de répéter la totalité de cette instruction, on va:

* lui donner un nom
* puis la remplacer par ce nom à chaque fois qu’elle est utilisée.

link:https://trinket.io/library/trinkets/7eb2dd4a2f[Ce qui donne.]

=== Corps d'une fonction

L’instruction
[source,python]
----
print("----------------------------------------")
print()
print()
----
que l’on isole par la définition de la fonction tirer_trait s’appelle le
*corps* de cette fonction.

== Appel d’une fonction

L’instruction `tirer_trait()` s’appelle un appel de la fonction `tirer_trait`.
Exécuter cette instruction a pour effet d’exécuter le corps de la fonction.

=== !

On remarque que le reste du code est très proche, mais pas identique.

On va paramétrer l’instruction que l’on isole pour pouvoir choisir la
destination et l’horaire du vol.

=== !

On parle *d'arguments* ou de *paramètres* de la fonction.
C'est un peu la même chose que la variable d'une fonction en mathématiques

=== !

[source,python]
----
def annoncer_vol(destination, horaire):
  print("Le vol en direction de ", destination, " décollera à ", horaire)
  tirer_trait()
----

link:https://trinket.io/library/trinkets/e0a45e111f[Ce qui donne.]

=== !

Nous avons déjà vu beaucoup de fonctions : `print()`, `type()`, `input()`, ...

== 2. Syntaxe


[source,python]
----
def nomdelafcn(param1, param2, param3):
  bloc ...........................
  d instructions .................
  a realiser .....................
----

=== !

Une fonction peut ne pas avoir de paramètre, en avoir un, en avoir deux, ...

=== Sans paramètre

[source,python]
----
def bonjour():
  print("hello")
----

=== Retour

Une fonction peut aussi renvoyer un ou des objets avec l'instruction `return`.

[source,python]
----
def nomdelafcn(param1, param2, param3):
  bloc ...........................
  d instructions .................
  a realiser .....................
  return une expression
----

=== !

[source,python]
----
def somme(a, b):
  return a + b
----

[source,python]
----
>>> somme(3,4)
 7
----

== 3. Commentaires

Les commentaires sont des portions du code source ignorées par le compilateur ou l’interpréteur.

Ils sont, en général, utilisés pour rendre le code plus compréhensible.

[source,python]
----
#Je suis un commentaire
print("hey") #moi aussi
print("#pas moi, car je suis entre des guillements")
----

=== Commentaires et fonctions

Avec la syntaxe suivante:

[source,python]
----
def nomdelafcn(param1, param2, param3):
  """ Moi aussi je suis
  un commentaire """
  bloc ...........................
  d instructions .................
  a realiser .....................
  return une expression
----

On ajoute un commentaire sensé décrire la fonction et qui apparaitra dans l'aide.


== 4. Portée des variables

[%step]
* La portée d'une variable est l'endroit du programme où on peut accéder à la variable.
* Les variables définies dans le bloc d'instruction d'une fonction, n'ont qu'une portée locale.
* Autrement dit, leur contenu est inaccessible depuis l’extérieur de la fonction.

=== !

[source,python]
----
def f(x):
  carre = x ** 2
  return carre

print(carre)
----

Ce code produit l'erreur: NameError: name 'carre' is not defined

=== !

[source,python]
----
a = 10		# variable globale au programme

def mafonction():
    a = 20	# variable locale à la fonction
    print(a)
----

[source,python]
----
>>> a
 10
>>> mafonction()
 20
>>> a
 10
----

== VII. Utilisation d’un module

=== !

`import` permet d'accéder à des fonctions, variables... déjà codé. +
L’importation d’un module peut se faire de deux manières.

=== Méthode 1:

On désigne le module à importer par son nom, il faut préfixer par son nom à chaque fois:

[source,python]
----
import math
x = math.sqrt(4) #sqrt permet de calculer la racine carrée
y = math.cos(0)
print(x,y)
----

=== Méthode 2:

`from import` permet d'importer des fonctionnalités précises
Dans le cas d’un import de plusieurs fonctionnalités,les noms sont séparés par des virgules.

[source,python]
----
from math import sin, cos
x = sin(0)
print(x)
----

=== !

Enfin, il est possible d’importer, avec cette seconde approche,
tous les éléments d’un module en utilisant la notation *

[source,python]
----
from turtle import *
----

Attention, avec cette dernière forme car il peut il y avoir conflits entre les
noms.
