:backend: revealjs
:revealjs_theme: moon

= VIII. Listes
:source-highlighter: pygments
:pygments-style: tango

== Définition et syntaxe

Une liste est une "collection" d'objets indicés.

La syntaxe est la suivante:

[source,python]
----
>>> course = ["beurre","tomates","PQ" ]
----

=== !

[source,python]
----
>>> course = ["beurre","tomates","PQ" ]
>>> type(course)
<class 'list'>
----

Le type `list` est un type composite, il rassemble des objets d'autres types.

=== !

[source,python]
----
>>> ma_liste = [42, "toto", [4,5]]
----

Une liste peut contenir plusieurs types différents, dont des listes.

== Manipuler les listes

=== Accéder

On peut accéder à un élément particulier d'une liste à l'aide de son index dans la liste:

[source,python]
----
>>> course = ["beurre","tomates","PQ" ]
>>> course[2]
'PQ'
----

=== !

[source,python]
----
>>> course = ["beurre","tomates","PQ" ]
>>> course[0]
'beurre'
----

Attention on commence à compter à partir de 0.

=== Modifier

On peut modifier un élément de la liste de la sorte:

[source,python]
----
>>> course[1] = "carrotes"
>>> course
 ['beurre', 'carrotes', 'PQ']
----

=== Ajouter
On peut ajouter un élément à la fin de la liste de la sorte:

[source,python]
----
>>> course.append("lait")
>>> course
 ['beurre', 'carrotes', 'PQ', 'lait']
----

=== Supprimer

Et supprimer un élément selon son indice:
[source,python]
----
>>> del(course[2])
>>> course
 ['beurre', 'carrotes', 'lait']
----

=== Concaténer
On peut concaténer des listes avec les opérations + et *

[source,python]
----
>>> oubli = ["huile","PQ"]
>>> course = course + oubli
>>> course
 ['beurre', 'carrotes', 'lait', 'huile', 'PQ']
----

=== Mesurer

On peut obtenir la longueur d'une liste avec la fonction `len`

[source,python]
----
>>> len(course)
 5
----

=== Parcourir

On peut parcourir une liste de plusieurs façon:

[source,python]
----
>>> for i in course:
...     print(i)
...
beurre
carrotes
lait
huile
PQ
----


[source,python]
----
>>> for i in range(len(course)):
...     print(course[i])
...
beurre
carrotes
lait
huile
PQ
----

=== !

On peut créer une liste vide:
[source,python]
----
>>> ma_liste = []
----

== VIII. Compléments sur les chaînes de caractéres:

Les chaînes de caractères se comportent comme les listes, à l'exception
qu'elles ne sont pas modifiables.

=== !

On peut donc accéder au i-éme élément d'une chaîne de caractère _mot_ à l'aide de `mot[i]`
mais on ne peut pas modifier `mot[i]`.

[source,python]
----
>>> toto = "hello !"
>>> toto[0]
 'h'
----

=== !

On peut aussi par exemple, obtenir le nombre de caractère dans la chaîne:

[source,python]
----
>>> len(toto)
 7
----

=== !

Par contre `mot.append(_val_)` ou `del(mot[2])` ne vont pas marcher,
 car la chaîne n'est pas modifiable.

[source,python]
----
>>> toto.append("world")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'append'
----

=== !

On peut déterminer si un caractère appartient à une chaîne à l'aide de
l'opérateur in.

[source,python]
----
>>> "a" in "toto"
False
>>> "o" in "toto"
True
----

== Passer des chaînes de caractères aux listes et inversement


=== Transformer une chaîne de caractères en liste

La fonction `list` permet de transformer une chaîne de caractère en une liste.

[source,python]
----
>>> ma_liste = list("hello")
>>> ma_liste
['h', 'e', 'l', 'l', 'o']
----

=== Transformer une liste en une chaîne de caractères

La méthode `join` permet de concaténer une liste dans une chaîne de caractère.

[source,python]
----
>>> ma_chaine = "".join(["w","o","r","l","d"])
>>> ma_chaine
"world"
----

=== Application

[source,python]
----
mot = input("Entrez un mot:")
lettres = list(mot)
for i in range(len(lettres)):
    if lettres[i] == "a":
        lettres[i] = "@"
mot_affiche = "".join(lettres)
print(mot_affiche)
----
